package signing_test

import (
	"testing"
	"time"

	"github.com/sns45/anyhook/go/core"
	"github.com/sns45/anyhook/go/signing"
)

// compile-time assertion: CoreSigner satisfies core.WebhookSigner structurally,
// without signing importing core in non-test code (G1).
var _ core.WebhookSigner = signing.CoreSigner{}

// TestSignInteropVector asserts Sign produces EXACTLY the vector generated by
// the official-compatible TS signer, proving byte-identical wire compat with
// the standardwebhooks ecosystem.
func TestSignInteropVector(t *testing.T) {
	const (
		secret  = "whsec_AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
		id      = "msg_1"
		payload = `{"a":1}`
		want    = "v1,g9EIBBIwm31AQEkP7q60DV8jDWYbrjV7TTZJL+PIcMo="
	)
	ts := time.Unix(1700000000, 0).UTC()

	got, err := signing.Sign(secret, id, ts, payload)
	if err != nil {
		t.Fatalf("Sign returned error: %v", err)
	}
	if got != want {
		t.Fatalf("Sign() = %q, want %q", got, want)
	}
}

func TestSignerHeadersUseInteropVector(t *testing.T) {
	const (
		secret  = "whsec_AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
		id      = "msg_1"
		payload = `{"a":1}`
		want    = "v1,g9EIBBIwm31AQEkP7q60DV8jDWYbrjV7TTZJL+PIcMo="
	)
	ts := time.Unix(1700000000, 0).UTC()

	hdrs, err := signing.NewSigner(secret).Headers(id, payload, ts)
	if err != nil {
		t.Fatalf("Headers returned error: %v", err)
	}
	if hdrs["webhook-signature"] != want {
		t.Fatalf("webhook-signature = %q, want %q", hdrs["webhook-signature"], want)
	}
	if hdrs["webhook-id"] != id {
		t.Fatalf("webhook-id = %q, want %q", hdrs["webhook-id"], id)
	}
	if hdrs["webhook-timestamp"] != "1700000000" {
		t.Fatalf("webhook-timestamp = %q, want %q", hdrs["webhook-timestamp"], "1700000000")
	}
}

func TestSignerMultiSecretSpaceJoined(t *testing.T) {
	ts := time.Unix(1700000000, 0).UTC()
	s1, err := signing.Sign("whsec_AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB", "msg_1", ts, `{"a":1}`)
	if err != nil {
		t.Fatal(err)
	}
	s2, err := signing.Sign("whsec_AgIBAQEBAQEBAQEBAQEBAQEBAQEBAQEB", "msg_1", ts, `{"a":1}`)
	if err != nil {
		t.Fatal(err)
	}

	hdrs, err := signing.NewSigner("whsec_AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB", "whsec_AgIBAQEBAQEBAQEBAQEBAQEBAQEBAQEB").
		Headers("msg_1", `{"a":1}`, ts)
	if err != nil {
		t.Fatal(err)
	}
	want := s1 + " " + s2
	if hdrs["webhook-signature"] != want {
		t.Fatalf("webhook-signature = %q, want %q", hdrs["webhook-signature"], want)
	}
}

func TestSignAcceptsSecretWithoutPrefix(t *testing.T) {
	ts := time.Unix(1700000000, 0).UTC()
	withPrefix, err := signing.Sign("whsec_AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB", "msg_1", ts, `{"a":1}`)
	if err != nil {
		t.Fatal(err)
	}
	withoutPrefix, err := signing.Sign("AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB", "msg_1", ts, `{"a":1}`)
	if err != nil {
		t.Fatal(err)
	}
	if withPrefix != withoutPrefix {
		t.Fatalf("signature should be identical with/without whsec_ prefix: %q vs %q", withPrefix, withoutPrefix)
	}
}

func TestGenerateSecret(t *testing.T) {
	s, err := signing.GenerateSecret(0)
	if err != nil {
		t.Fatal(err)
	}
	if len(s) <= len(signing.SecretPrefix) {
		t.Fatalf("generated secret too short: %q", s)
	}
	if s[:len(signing.SecretPrefix)] != signing.SecretPrefix {
		t.Fatalf("generated secret missing prefix: %q", s)
	}
	key, err := signing.ParseSecret(s)
	if err != nil {
		t.Fatalf("ParseSecret(generated secret) failed: %v", err)
	}
	if len(key) != signing.DefaultSecretBytes {
		t.Fatalf("parsed key length = %d, want %d", len(key), signing.DefaultSecretBytes)
	}
}
